'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ImageView
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''imgbtnNavDocFastRewind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnNavDocFastRewind As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbtnPreviousNavDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnPreviousNavDoc As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtNavDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNavDoc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNavDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNavDoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgbtnNextNavDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnNextNavDoc As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbtnNavDocFastForword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnNavDocFastForword As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbtnFastRewind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnFastRewind As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbtnPreviousNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnPreviousNav As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNav As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNav As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgbtnNextNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnNextNav As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbtnFastForword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnFastForword As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbtnAnnotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnAnnotation As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblHVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHVersion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlAnnotationVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAnnotationVersion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgbtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnBack As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDetID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDetID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlImageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImageView As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''documentViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents documentViewer1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''pnlDocView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocView As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDoucmentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDoucmentType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHFileName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkOpenDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOpenDocument As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblFileTypeH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileTypeH As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFileType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCreatedByH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedByH As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCreatedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCreatedOnH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedOnH As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCreatedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedOn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSizeH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSizeH As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSize As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dgIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgIndex As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''txtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPreId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPreId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lstDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDocument As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lstFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstFiles As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblDocID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFileID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSearchImageViewValidationMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchImageViewValidationMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
